import { useState } from "react";
import Card from "../components/Card";




const Home = () => {
    const [search,setSearch]=useState('')
    const [sort,setSort]=useState('')
    const [show,setShow]=useState('Showing all posts ...')// Showing resultat of  ... 

    return ( 
    <div className="w-full mx-auto flex flex-col justify-center items-center">
        <div className="self-start w-[75%] mx-auto">
            <h1 className="font-extrabold text-[#222328] lg:text-[32px] md:text-[28px] sm:text-[24px] text-[20px] ">The Community Showcase</h1>
            <p className="mt-2 text-[#666e75] md:text-[14px] text-[10px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by AIArt</p>
         </div>
        <div className="flex justify-around w-[75%] mx-auto items-center mt-10">
            <div className="flex flex-col justify-center items-start w-[75%]">
                <label htmlFor="search" className="opacity-85 lg:text-[16px] md:text-[14px] sm:text-[12px] text-[10px]" > Search Posts</label>
                <input name="search" type="search" placeholder="Synthwave aeroplane" value={search} onChange={(e)=>{setSearch(e.target.value)}} className="bg-[#C3B5B5] lg:text-[16px] md:text-[14px] sm:text-[12px] text-[10px] w-full rounded-md text-[#000] p-2" />
            </div>      
            <div  className="flex flex-col justify-center items-start ">
                    <label htmlFor="sort" className="opacity-85 lg:text-[16px] md:text-[14px] sm:text-[12px] text-[10px]" > Sort By </label>
                    <select value={sort} onChange={(e)=>{setSort(e.target.value)}} name="sort" id="sort" className="lg:text-[16px] md:text-[14px] sm:text-[12px] text-[10px] hover:cursor-pointer rounded-md p-2 bg-[#C3B5B5]">
                        <option value="rating">Rating</option>
                        <option value="view">Most View</option>
                        <option value="title" >Title</option>
                    </select>
            </div>
        </div>
        <h3 className="font-bold lg:text-[16px] md:text-[14px] sm:text-[12px] text-[10px] mt-5">{show}</h3>
        
    <div className="carousel w-full">
    <div id="slide1" className="carousel-item relative w-full">
        <div className="grid grid-cols-3  mt-10 gap-5 mx-auto">
            <Card />
            <Card />
            <Card />
        </div>
        <div className="absolute flex justify-between items-center transform -translate-y-1/2 left-5 right-5 top-1/2">
        <a href="#slide4" className="btn btn-circle cursor-not-allowed" disabled>❮</a> 
        <a href="#slide2" className="btn btn-circle">❯</a>
        </div>
    </div> 
    <div id="slide2" className="carousel-item relative w-full flex justify-around">
            <div className="grid grid-cols-3  mt-10 gap-5 mx-auto">
                <Card />
                <Card />
                <Card />
            </div>
            <div className="absolute flex justify-between items-center transform -translate-y-1/2 left-5 right-5 top-1/2">
            <a href="#slide1" className="btn btn-circle ">❮</a> 
            <a href="#slide3" className="btn btn-circle">❯</a>
            </div>
    </div> 
    <div id="slide3" className="carousel-item relative w-full">
    <div className="grid grid-cols-3  mt-10 gap-5 mx-auto">
            <Card />
            <Card />
            <Card />
        </div>
            <div className="absolute flex items-center justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
        <a href="#slide2" className="btn btn-circle">❮</a> 
        <a href="#slide4" className="btn btn-circle">❯</a>
        </div>
    </div> 
    <div id="slide4" className="carousel-item relative w-full">
    <div className="grid grid-cols-3  mt-10 gap-5 mx-auto">
            <Card />
            <Card />
            <Card />
        </div>
            <div className="absolute flex items-center justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
        <a href="#slide3" className="btn btn-circle">❮</a> 
        <a href="#slide1" className="btn btn-circle cursor-not-allowed" disabled>❯</a>
        </div>
    </div>
    </div>

    </div> );
}
 
export default Home;

